### ISSUE TITLE
Error in install_beast2_pkg("NS")

### ISSUE THREAD

**Issue by thijsjanzen** [ropensci/mauricer#4]
Required to make mcbette function, I executed the following (and received an error):

```
> mauricer::install_beast2_pkg("NS")
Error: Could not find or load main class beast.util.PackageManager
Error in if (is_beast2_pkg_installed(name)) { : 
  argument is of length zero
In addition: Warning message:
In system2(command = beastier::get_default_java_path(), args = c("-cp",  :
  running command ''/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' -cp '/Users/janzen/Library/Application Support/BEAST/lib/beast.jar' beast.util.PackageManager -list' had status 1
```

I run R 3.5.2 from Rstudio, on MacOS:
```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

```

**Comment by richelbilderbeek** [comment]
Thanks for this Issue! I predict this is not a `mcbette` Issue, but more related to your local setup. Still, cool to have such errors documented someplace :+1: 

I assume the OS is Mac. I see [in the mcbette build log (running on MacOS)](https://travis-ci.org/richelbilderbeek/mcbette/jobs/498167878#L1342) there is no problem. It will be hard for me to fix a problem I cannot reproduce.

I predict if you run (thanks to the helpful error message):

```
'/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' -cp '/Users/janzen/Library/Application Support/BEAST/lib/beast.jar' beast.util.PackageManager -list
```

this returns nothing and/or an error.

Posting the result of running that give me a hint how to solve your problem. I predict it will indicate a problem with either Java or the spaces in the path. 

Let me know :rainbow:

**Comment by thijsjanzen** [comment]
This results in "nothing", although it seems something is started, but only a new cursor is started:
[https://imgur.com/1VITg2I](url)

I also predict it might be a Java issue - although the spaces in the path look terrifying as well, this is a very common folder on OS X (Application Support), which leads me to suspect it *should* be all right.

**Comment by richelbilderbeek** [comment]
Hmmm, maybe

```
'/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' --version
```

(or the likes) give some more insights...

Note you can add pictures directly to an Issue, below the Issue message you can 'Attach files by dragging ...':

![error](https://user-images.githubusercontent.com/2098230/53965010-aff66500-40f0-11e9-9826-5076be851c8c.jpg)

**Comment by thijsjanzen** [comment]
Same result:   >

<img width="697" alt="screenshot 2019-03-07 16 10 28" src="https://user-images.githubusercontent.com/19486664/53966509-96a2e800-40f3-11e9-81f4-615112499a0e.png">

**Comment by richelbilderbeek** [comment]
You forgot to start with the single quote in your command:

```
'/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' --version
^
|
here
```

What would happen if you would add it :rainbow: :+1:

**Comment by thijsjanzen** [comment]
<img width="697" alt="screenshot 2019-03-07 22 18 16" src="https://user-images.githubusercontent.com/19486664/53989743-f4045c80-4126-11e9-9eeb-4a3110ebe247.png">

(although the file *is* there on the hard drive, I just checked)
<img width="749" alt="screenshot 2019-03-07 22 20 43" src="https://user-images.githubusercontent.com/19486664/53989874-48a7d780-4127-11e9-800a-5c121a417d63.png">

So... something else is wrong, it turns out it should be -version, not --version: 

<img width="1299" alt="screenshot 2019-03-07 22 22 28" src="https://user-images.githubusercontent.com/19486664/53989994-8d337300-4127-11e9-80ee-3e8cd7d24507.png">

**Comment by thijsjanzen** [comment]
So, repeating the first command (notice that I also fixed the empty space, but to no avail):
<img width="939" alt="screenshot 2019-03-07 22 29 20" src="https://user-images.githubusercontent.com/19486664/53990404-80634f00-4128-11e9-893d-1f5df89e4b9e.png">

The beast.jar file is actually there, so that is not the issue, there must be something else...
<img width="749" alt="screenshot 2019-03-07 22 27 53" src="https://user-images.githubusercontent.com/19486664/53990427-8f4a0180-4128-11e9-819d-89d6a336ea80.png">

I do notice that these files are 3 years old - perhaps these are BEAST files from an old installation (or a BEAST 1 installation?), which have never been updated somehow?

running edit: no, that is also not the issue, if I replace the path with a path to another BEAST installation, I retain the error message:
<img width="939" alt="screenshot 2019-03-07 22 37 26" src="https://user-images.githubusercontent.com/19486664/53990913-ac330480-4129-11e9-81c2-2c8f51821366.png">

**Comment by richelbilderbeek** [comment]
Thanks for the help and the screenshots!

> I do notice that these files are 3 years old - perhaps these are BEAST files from an old installation (or a BEAST 1 installation?), which have never been updated somehow?

This is no problem in many other contexts. Those files are used for months on Travis (both Linux and Mac), and also by projects that build on `mcbette`.

I assume you have an internet connection ...

Perhaps Albertas Janulevicius (in Sander's group) has an idea? He uses Java more than I do.

**Comment by richelbilderbeek** [comment]
This is what I get when I `grep` for `PackageManager`:

```
richel@oldskool:~/.local/share/beast$ egrep -R "PackageManager"
bin/packagemanager:"$JAVA" -Xms256m -Xmx1024m -Djava.library.path="$BEAST_LIB" -Duser.language=en -cp "$BEAST_LIB/beast.jar" beast.util.PackageManager $*
Binary file lib/beast.src.jar matches
Binary file lib/beast.jar matches
Binary file lib/launcher.jar matches
```

What do you get?

**Comment by thijsjanzen** [comment]
grep or egrep doesn't do anything and just stalls (with or without -R, e.g. grep bin/pacakgemanager also stalls)

<img width="883" alt="Screenshot 2019-03-09 08 17 52" src="https://user-images.githubusercontent.com/19486664/54067721-ebee0f00-4243-11e9-9c69-ae725169facb.png">

**Comment by richelbilderbeek** [comment]
What if you search in any other way for the word `PackageManager` in the BEAST2 folder?

**Comment by richelbilderbeek** [comment]
What does, when in R, this give:

```r
beastier::get_default_beast2_jar_path()
```

**Comment by thijsjanzen** [comment]
> What does, when in R, this give:
> 
> ```r
> beastier::get_default_beast2_jar_path()
> ```

"/Users/janzen/Library/Application Support/BEAST/lib/beast.jar"


> What if you search in any other way for the word `PackageManager` in the BEAST2 folder?

<img width="865" alt="Screenshot 2019-03-12 at 09 19 14" src="https://user-images.githubusercontent.com/19486664/54184868-f27cc080-44a7-11e9-91fb-9866a0eff242.png">

**Comment by richelbilderbeek** [comment]
> What if you search in any other way for the word PackageManager in the BEAST2 folder?

My bad:

What if you search in any other way for the word PackageManager **within the files** (their content) in the BEAST2 folder?

**Comment by thijsjanzen** [comment]
<img width="662" alt="Screenshot 2019-03-12 at 10 28 36" src="https://user-images.githubusercontent.com/19486664/54189232-a6cf1480-44b1-11e9-8575-9462402b929d.png">

I guess you mean this? (the * was missing before... grep/egrep needs a second argument, otherwise it just waits)

**Comment by richelbilderbeek** [comment]
Could you try

```
egrep -R "PackageManager" --include=*.jar
```

When I do:

```
richel@oldskool:~/.local/share/beast$ egrep -R "PackageManager" --include=*.jar
Binary file lib/beast.src.jar matches
Binary file lib/beast.jar matches
Binary file lib/launcher.jar matches
```

For reference, when I do a full search (no need of an asterisk here):

```
richel@oldskool:~/.local/share/beast$ egrep -R "PackageManager"
bin/packagemanager:"$JAVA" -Xms256m -Xmx1024m -Djava.library.path="$BEAST_LIB" -Duser.language=en -cp "$BEAST_LIB/beast.jar" beast.util.PackageManager $*
Binary file lib/beast.src.jar matches
Binary file lib/beast.jar matches
Binary file lib/launcher.jar matches
```

I wonder if the `jar` files are missing...

**Comment by richelbilderbeek** [comment]
Actually, this screenshot show those `jar`s are there:

The beast.jar file is actually there, so that is not the issue, there must be something else...
<img width="749" alt="screenshot 2019-03-07 22 27 53" src="https://user-images.githubusercontent.com/19486664/53990427-8f4a0180-4128-11e9-819d-89d6a336ea80.png">

Now I ran out of hypotheses ...

**Comment by richelbilderbeek** [comment]
@thijsjanzen: were you able to solve this Issue?

**Comment by richelbilderbeek** [comment]
I assume yes :rainbow:
